### ISSUE TITLE
学習がうまく進まない

### ISSUE THREAD

**Issue by asao-kanta** [jjjkkkjjj/pytorch.dl#11]
こんばんは、こちらのコードを拝借して転移学習を試みておりますが学習がうまくいかないため質問させてください。
学習にはdebug/fots/train.pyを使用し、モデルの読み込みの下に以下のコードを入れて実行しております。
```
model.load_weights('./sample_weights/fots-pretrain_model.pth')
```
エラーはpytorchのctc_lossで起きております。
```
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    trainer.train_epoch(save_manager, 10, train_loader)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\log\trainer.py", line 95, in train_epoch
    self._train(savemanager, max_iterations, train_loader, start_iteration)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\log\trainer.py", line 123, in _train
    names, losses = self.learn(*item)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\log\trainer.py", line 335, in learn
    return _learn_txtspotting(self, images, targets, texts)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\log\trainer.py", line 322, in _learn_txtspotting
    loss, detn_loss, recog_loss = self.loss_module(detn, recog)
  File "C:\Users\kd207\miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\loss\fots.py", line 41, in forward
    recog_loss = self.recog_loss(*recog)
  File "C:\Users\kd207\miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\kd207\Desktop\gleap\ocr\torchdl\dl\loss\fots.py", line 231, in forward
    loss = F.ctc_loss(predicts[0], targets[0], predict_lengths[0], target_lengths[0], blank=self.blankIndex, reduction='mean', zero_infinity=True)
  File "C:\Users\kd207\miniconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1780, in ctc_loss
    return torch.ctc_loss(log_probs, targets, input_lengths, target_lengths, blank, _Reduction.get_enum(reduction),
RuntimeError: target_lengths must be of size batch_size
```

ctc_lossへの入力は以下の通りです。
```
p : torch.Size([21, 2, 69])
t : torch.Size([4, 5])
p_l : torch.Size([2])
t_l : torch.Size([4])
```

使用データセットは独自のもので、画像とアノテーションファイルは公開できません。
もし必要な場合は言ってください。

何かわかりましたら幸いです。
よろしくお願いします。

**Comment by jjjkkkjjj** [comment]
返信が遅くなり，申し訳ございません．
そして，使っていただきありがとうございます．

CTCLossのコメントを見ると，以下のようになっているので，画像内の予測時の文字数が違うようですね．
随分前なので記憶が曖昧なのですが，学習時では揃うように実装しているはずです．．．


```python
"""
:param predicts: list(b) of predicted text number Tensor, shape = (times, text nums, class_nums)
:param targets: list(b) of true text number Tensor, shape = (true text nums, char nums)
:param predict_lengths: list(b) of length Tensor, shape = (text nums)
:param target_lengths: list(b) of true length Tensor, shape = (true text nums)
:return: loss: loss Tensor, shape = (b,)
"""
```

Lossに渡す前の，
https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/models/fots/base.py#L158
の
- `rotated_features: [Tensor]`の`shape`
- `labels: [Tensor]`の`shape`
- `texts: [Tensor]`の`shape`
をそれぞれご確認いただけないでしょうか？

**Comment by jjjkkkjjj** [comment]
もしかしたら，入力に渡す`labels`と`texts`の`shape`があっていないのが原因かもしれません．

**Comment by asao-kanta** [comment]
返信ありがとうございます。
それぞれリストなので要素ごとのsizeを出力しました。

```
rotated_features
[torch.Size([4, 32, 8, 26]), torch.Size([4, 32, 8, 23])]

labels
[torch.Size([4, 13]), torch.Size([4, 13])]

texts
encode前 : [[tensor([13], dtype=torch.int32), tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([2, 2, 6, 6, 9], dtype=torch.int32), tensor([ 2, 32, 20,  3,  6], dtype=torch.int32)], [tensor([13], dtype=torch.int32), tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([ 1,  9, 10,  2,  9], dtype=torch.int32), tensor([ 2, 32, 19,  6,  3], dtype=torch.int32)]]
encode後 : [torch.Size([4, 5]), torch.Size([4, 5])]
```
モデルからの出力が別のものになったのでctc_lossへの入力は以下です。
```
p : torch.Size([20, 1, 69])
t : torch.Size([4, 5])
p_l : torch.Size([1])
t_l : torch.Size([4])
```

qiitaにも質問させていただいたのですが、この原因はモデルが矩形取りに失敗した文字の出力がないのに、正解ラベルはあることだと思ってるのですが、いかがでしょうか。
https://qiita.com/jjjkkkjjj/items/bfa03d89eaf6ab0c0487#comment-f7ef7502622cf4cc2858

**Comment by asao-kanta** [comment]
なので矩形取りに失敗したものについては正解ラベルを削除してあげないといけない？のかなと、、、
方法は思いつきませんが。

**Comment by jjjkkkjjj** [comment]
> 正解ラベルはあることだと思ってるのですが、いかがでしょうか。
はい，その認識で間違いないと思います．

`rotated_features`の`shape=torch.Size([4, 32, 8, 26])`で正解ラベルの`shape=torch.Size([4, 5])`なので，短形取りには失敗していないはずです．（学習の際は，正解ラベルから特徴マップを短形取りするので，失敗しないはずです．）

認識器のCRNNのバグかもしれませんね．．．

上記，コードの`true_quads`を表示していただけませんか？
もしかしたら，quadsの領域がおかしいかもしれません，

```
# RoI Rotate Branch
# list(b) of Tensor, shape = (text nums, c, height=8, non-fixed width)
true_quads = [l[:, 4:12] for l in labels]
rotated_features = self.roi_rotate(fmaps, true_quads)
```

**Comment by jjjkkkjjj** [comment]
> この原因はモデルが矩形取りに失敗した文字の出力がないのに、正解ラベルはあることだと思ってるのですが、いかがでしょうか。

はい，その認識で合ってると思います．
ただ，学習の際は，正解ラベルの短形を用いるので，短形取りが失敗するはずがないのです．．．
同様に，以下の

https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/models/fots/base.py#L168

```python
# ps: shape = (times, text_nums, class_labels)
# ts: LongTensor, shape = (text_nums, max length of text)
# pred_lengths: LongTensor, shape = (text_nums,)
# t_lengths: LongTensor, shape = (text_nums,)
preds, ts, pred_lengths, t_lengths
```

`preds, ts, pred_lengths, t_lengths`と`rotated_features[b], texts[b]`をの`shape`を表示していただけないでしょうか？
これで`shape`がずれているなら，認識器のCRNNのバグの可能性が高くなります．

**Comment by asao-kanta** [comment]
なるほど、文字認識の学習の際には画像の正解矩形部分を入力として渡しているんですね！
読み込みが甘かったです。

```
true quads size
[torch.Size([4, 8]), torch.Size([4, 8])]
```
```
true quads
[tensor([[0.3144, 0.3809, 0.3464, 0.3823, 0.3448, 0.4446, 0.3128, 0.4432],
        [0.4033, 0.3587, 0.4881, 0.3623, 0.4871, 0.4008, 0.4023, 0.3972],
        [0.3806, 0.4008, 0.4879, 0.4054, 0.4869, 0.4450, 0.3796, 0.4404],
        [0.3820, 0.4485, 0.4884, 0.4530, 0.4875, 0.4893, 0.3811, 0.4847]]), tensor([[0.6631, 0.0672, 0.7208, 0.0672, 0.7208, 0.2116, 0.6631, 0.2116],
        [0.8222, 0.0041, 0.9778, 0.0041, 0.9778, 0.0943, 0.8222, 0.0943],
        [0.7873, 0.1093, 0.9813, 0.1093, 0.9813, 0.2116, 0.7873, 0.2116],
        [0.7908, 0.2252, 0.9813, 0.2252, 0.9813, 0.3139, 0.7908, 0.3139]])]
```
```
features[b] size
b = 0
torch.Size([2, 32, 8, 24]) 
b = 1
torch.Size([4, 32, 8, 21])
```
```
texts[b]
b = 0
[tensor([13], dtype=torch.int32), tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([ 1,  9, 10,  2,  9], dtype=torch.int32), tensor([ 2, 32, 19,  6,  3], dtype=torch.int32)] 

b = 1
[tensor([13], dtype=torch.int32), tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([2, 2, 6, 6, 9], dtype=torch.int32), tensor([ 2, 32, 20,  3,  6], dtype=torch.int32)] 
```
```
qreds, ts, pred lengths, t lengths size
b = 0
torch.Size([24, 2, 69]) torch.Size([4, 5]) torch.Size([2]) torch.Size([4]) 
b = 1
torch.Size([21, 4, 69]) torch.Size([4, 5]) torch.Size([4]) torch.Size([4]) 
```

こちらになります、よろしくお願いします。

**Comment by asao-kanta** [comment]
たまに学習が成功するときがあるのですが、その時の出力が以下のようになっております。
```
quad size
[torch.Size([3, 8]), torch.Size([4, 8])]
```
```
quads
[tensor([[0.1187, 0.4864, 0.3054, 0.4864, 0.3054, 0.5298, 0.1187, 0.5298],
        [0.0768, 0.5370, 0.3096, 0.5370, 0.3096, 0.5862, 0.0768, 0.5862],
        [0.0810, 0.5927, 0.3096, 0.5927, 0.3096, 0.6353, 0.0810, 0.6353]]), tensor([[0.1696, 0.7233, 0.2966, 0.7165, 0.3161, 0.8145, 0.1890, 0.8213],
        [0.5117, 0.6635, 0.8483, 0.6455, 0.8604, 0.7061, 0.5238, 0.7241],
        [0.4393, 0.7359, 0.8652, 0.7131, 0.8776, 0.7755, 0.4517, 0.7983],
        [0.4645, 0.8102, 0.8869, 0.7876, 0.8983, 0.8446, 0.4758, 0.8673]])]
```
```
b = 0
features size
torch.Size([3, 32, 8, 43])

texts 
[tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([2, 2, 6, 6, 9], dtype=torch.int32), tensor([ 2, 32, 20,  3,  6], dtype=torch.int32)]

qreds, ts, pred lengths, t lengths size
torch.Size([43, 3, 69]) torch.Size([3, 5]) torch.Size([3]) torch.Size([3])

b = 1
features size
torch.Size([4, 32, 8, 60])

texts 
[tensor([13], dtype=torch.int32), tensor([ 3, 14,  1, 10], dtype=torch.int32), tensor([ 1,  9, 10,  2,  9], dtype=torch.int32), tensor([ 2, 32, 19,  6,  3], dtype=torch.int32)]

qreds, ts, pred lengths, t lengths size
torch.Size([60, 4, 69]) torch.Size([4, 5]) torch.Size([4]) torch.Size([4])
```

**Comment by jjjkkkjjj** [comment]
ありがとうございます．

１枚の画像に短形領域が4つあるにもかかわらず，

```python
true quads size
[torch.Size([4, 8]), torch.Size([4, 8])]
```

ROI_Rotate後の`features`画像の数が２つになって，合っていないですね．

```python
features[b] size
b = 0
torch.Size([2, 32, 8, 24]) 
b = 1
torch.Size([4, 32, 8, 21])
```

なので，`ROI_Rotate`の出力で２個分の短形領域が消滅してしまっていることが原因なようです．
https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/models/fots/modules/roi.py#L35

何度も申し訳ないのですが，

https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/models/fots/modules/roi.py#L34
の`text_nums`と`_quads.shape`と`quads[b].shape`
をご確認いただけないでしょうか？

`text_nums`が２になってしまっている？

**Comment by jjjkkkjjj** [comment]
あと考えられるのが，`quads`で表される短形領域が四角形をなしていない（ソートされていない等）ことですが，パッと見た感じだと正しくtop-left→bottom-rightになっているようです．

**Comment by asao-kanta** [comment]
バグの原因がありました。
最初に推論を実行したときに矩形が小さいものを除きたくてとりあえずで挟んでいた以下のコードをそのままにしておりました。。
`_quads = [_q.reshape((4, 2)) for _q in _quads if cv2.contourArea(_q.reshape((4, 2))) > 90]`
これのせいで学習時に矩形が消えてしまっていたんですね。

ご丁寧にありがとうございました！お時間を取らせてしまって申し訳ありませんでした！

こちらで閉じておきます。

**Comment by jjjkkkjjj** [comment]
原因見つかったようで，よかったです！
小さいものを除去する場合は，それに対応する`labels`，`texts`も除去しないといけなさそうです．

全ての正解データを除去する可能性があるので，`target_transforms`で除去するのが理想的です．
classを作ってあげて，正解データがない場合は，`Ignore.NoLabelsError`を吐くようにすると，データを取得し直してくれます．

https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/data/txtdetn/target_transforms.py#L93

https://github.com/jjjkkkjjj/pytorch.dl/blob/d82aa1191c14f328c62de85e391ac6fa1b4c7ee3/dl/data/txtdetn/target_transforms.py#L120

**Comment by asao-kanta** [comment]
なるほど、ありがとうございます！
構造考えながらいろいろ試したいと思います！
何から何までありがとうございました！！
